# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [42]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [43]:
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [44]:
zeros = np.zeros((1,10))
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. How to find the memory size of any array (★☆☆)

In [45]:
print(zeros.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [46]:
np.lookfor ("add")

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy.array_api.add
    Array API compatible wrapper for :py:func:`np.add <numpy.add>`.
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return a left-j

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [47]:
x = np.zeros(10)
x[4] = 1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [48]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [49]:
A = np.array([[1,2,3],[4,5,6]])
np.flip(A)

array([[6, 5, 4],
       [3, 2, 1]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [50]:
k = np.arange(9).reshape(3, 3)
print(k)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [51]:
x = np.array([1, 2, 0, 0, 4, 0])
result = np.nonzero(x)
print(result)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
np.random.random((3,3,3))

array([[[0.94031152, 0.99534658, 0.65546319],
        [0.27449731, 0.49412229, 0.20522699],
        [0.75364878, 0.96399809, 0.33881689]],

       [[0.14700983, 0.98332211, 0.75629271],
        [0.59359391, 0.15183044, 0.52549445],
        [0.98948038, 0.74904366, 0.40688265]],

       [[0.56631254, 0.20073274, 0.47357321],
        [0.54514676, 0.59107636, 0.70125536],
        [0.72777499, 0.1169864 , 0.96044752]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
a = np.random.random((10,10))
print(a)
print("min =", a.min())

[[5.96065282e-01 3.04800905e-01 5.60323681e-01 1.37784560e-01
  8.51809934e-02 4.98758365e-01 1.86880031e-01 3.58859622e-01
  1.49612556e-01 2.74891633e-01]
 [1.45222392e-01 4.96535838e-01 3.04747892e-01 4.07006946e-01
  3.95378251e-01 2.60663185e-01 7.07798219e-04 7.25738985e-01
  4.56336789e-02 9.47479270e-01]
 [1.14402589e-01 9.68147461e-01 9.35453092e-01 2.20374621e-02
  4.75995163e-01 1.00066933e-01 6.63296161e-01 9.79439140e-01
  7.35379006e-01 6.53767765e-01]
 [2.23744651e-01 6.95194423e-01 1.00963246e-01 7.44830794e-01
  5.68758799e-01 6.69924441e-01 3.60962487e-01 4.86777510e-01
  8.46938705e-01 1.63773177e-01]
 [9.45882296e-01 6.63442415e-01 3.22758537e-01 7.60645658e-02
  1.28764744e-02 5.85709330e-01 9.24000514e-01 1.20177673e-01
  4.42337204e-01 4.04598071e-01]
 [5.40917449e-01 6.25214057e-01 6.26623714e-01 8.87823989e-01
  2.99416809e-01 6.23017800e-01 2.99571398e-01 2.83528960e-01
  1.66542371e-01 9.86996444e-01]
 [1.40786556e-01 9.72079779e-02 9.07043250e-01 9.31583000e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [55]:
x = np.random.random(30)
print(x)
print("mean =", x.mean())

[0.63431025 0.15341058 0.78423508 0.18860832 0.18470366 0.99228914
 0.48988477 0.35662313 0.2958998  0.46821053 0.44957628 0.93936818
 0.6161117  0.71267005 0.62050082 0.28062894 0.67396271 0.44154366
 0.46000737 0.5487132  0.34150404 0.63255162 0.75819991 0.64383756
 0.05561681 0.16596137 0.11269073 0.05363763 0.11974034 0.8345852 ]
mean = 0.46698611273130514


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [56]:
a = np.ones((3,3))
a[1,1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [57]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [58]:
print(0  * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
a = np.diag((1,2,3,4), -1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
# (odd_rows, even_columns)
x[1::2,::2] = 1
# (even_rows, odd_columns)
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [61]:
a = np.unravel_index([100], (6, 7, 8))
print(a)

(array([1]), array([5]), array([4]))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [62]:
import numpy as np
a = np.array([[0,1], [1,0]])
print(np.tile(a, (4, 4)))


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [63]:
x = np.random.random((5, 5))
norm = np.linalg.norm(x)
normal_x = x/norm
print(normal_x)

[[0.16639149 0.18952556 0.03029772 0.03587764 0.1890809 ]
 [0.24843748 0.19896533 0.27168615 0.05882193 0.14281614]
 [0.10232237 0.35017968 0.24928959 0.10764288 0.13213173]
 [0.29737584 0.06832666 0.22650505 0.21773385 0.17163948]
 [0.22394087 0.26661096 0.2212174  0.2337542  0.17055652]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [64]:
dt = np.dtype([('R','u1'), ('G','u1'), ('B','u1'), ('A','u1')])
x = dt.itemsize
print(x)

4


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [3]:
import numpy as np
x = np.random.random((5,3))
print("First array:\n", x)
y = np.random.random((3,2))
print("Second array:\n", y)
z = np.dot(x, y)
print("Dot product of two arrays:\n", z)

First array:
 [[0.97101412 0.97569246 0.55036544]
 [0.79775161 0.47012362 0.9168224 ]
 [0.22082621 0.78747265 0.44101517]
 [0.8077089  0.69311063 0.9941932 ]
 [0.11499156 0.69637217 0.94967978]]
Second array:
 [[0.82768638 0.83101466]
 [0.11420362 0.71178858]
 [0.71584793 0.20536038]]
Dot product of two arrays:
 [[1.30910074 1.61443697]
 [1.37028338 1.1858509 ]
 [0.58840687 0.8345909 ]
 [1.45937654 1.36873406]
 [0.85453147 0.78625603]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [66]:
x = np.arange(15)
#x = np.negative(x, 3-8)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [68]:
Z = np.random.randint(10, size=(5))
print(Z)
z = Z**Z
print(z)
z = 2 << Z >> 2
print(z)
z = Z <- Z #False output
print(z)
z = 1j * Z
print(z)
z = Z/1/1
print(z)
z = Z<Z>Z #creates error
print(z)




[1 0 0 5 3]
[   1    1    1 3125   27]
[ 1  0  0 16  4]
[False False False False False]
[0.+1.j 0.+0.j 0.+0.j 0.+5.j 0.+3.j]
[1. 0. 0. 5. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array ? (★☆☆)

In [4]:
test = np.array([32.11, 51.5, 0.112])
print(np.round(test,1))

[32.1 51.5  0.1]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
ar1 = np.array([12, 14, 15, 16, 17])
ar2 = np.array([2, 4, 5, 6, 7, 8, 9, 12])
  
print(np.intersect1d(ar1, ar2))